chore: 공통 api 구현
eylo-project/eylo-taxi-api pull request #7
Opened 2022-10-31 09:48 UTC by kkangmj

Resolve #5

2022-10-31 09:51 UTC, kkangmj commented
공통 response는 presentation layer에서만 사용되니까 presentation 아래 넣어놨음. 그리고 presentation layer에서 공통적으로 사용되는 거니까 common 만들어서 넣어도 될 것 같은데 지금 당장은 하나니까 굳이 싶어서 빼놨구.

2022-10-31 11:03 UTC, lyle0101 requested changes

2022-10-31 11:03 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        val data: T?,
코틀린에서 제네릭은 기본적으로 Any? 가 들어갈 수 있어서 T에 ?를 안붙여도 됐던 걸로 기억하는데 확인 한 번만 부탁드려요!

2022-10-31 11:03 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        }
아마 200 응답에 사용하려고 이 메서드를 추가하신 것 같은데 data 가 없는 상태로 200 을 리턴하는 경우도 있어야 하지 않을까요?

2022-10-31 11:03 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +            return ApiResponse(data, null);
코드 마지막에 세미콜론 지워주세요

2022-10-31 11:03 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +            return ApiResponse(null, throwable.message);
코드 마지막에 세미콜론 지워주세요

2022-10-31 11:03 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +            return ApiResponse(null, message);
코드 마지막에 세미콜론 지워주세요

2022-10-31 11:03 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +class ApiResponse<T> private constructor(
이거는 정해야 하는 건데, 전체적으로 코드 작성시에 한 줄씩 띄우는 걸 컨벤션으로 할까요 아니면 지금처럼 다 붙여놓는 걸로 할까요? 띄웠을 때 저는 보기가 더 좋다고 생각해서 여쭤봅니다!

2022-10-31 11:03 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +class ApiResponse<T> private constructor(
저희 에러코드 추가하기로 했었나요? 만약 추가하기로 했었으면 아래 companion object  메소드에 추후에라도 추가되어야 할 것 같긴 하네요

2022-10-31 11:03 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        fun ERROR(throwable: Throwable): ApiResponse<*> {
이 메서드는 필요한지 여부에 대해서 조금 고민이 되는데, 저희가 에러를 그대로 리턴하는 경우가 실제로 있을지와 있다고 하면 그게 옳은 방향인지도 궁금하네요!

2022-10-31 11:10 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +class ApiResponse<T> private constructor(
아뇨~ 추가 안 하기로 했었어요.

2022-10-31 11:11 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +class ApiResponse<T> private constructor(
이거가 정확하게 어떤 부분을 가리키는 걸까요? package와 class 사이의 간격을 말하는 건지, 생성자를 말하는 건지 구체적으로 알려주세요.

2022-11-01 04:31 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        val data: T?,
그렇네요! 공식 문서 찾아보니 디폴트로 upper bound가 Any?군요.

2022-11-01 06:52 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        }
추가할게요~

2022-11-01 06:54 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        fun ERROR(throwable: Throwable): ApiResponse<*> {
삭제했습니다~

2022-11-01 06:54 UTC, kkangmj commented
공통 api response를 잘 정의해둔 프로젝트가 있어서 올려요~
https://github.com/VNAPNIC/kotlin-spring-boot/blob/main/common/src/main/kotlin/com/vnapnic/common/entities/Response.kt

2022-11-01 10:18 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +class ApiResponse<T> private constructor(
붙이는 걸로 결정.

2022-11-02 03:54 UTC, kkangmj commented
[Singleton]
1. Object declaration
```
object Singleton {
    //singleton members
}
```

2. Initialization-on-demand hodler
```
class SingletonWithLazyAndObject private constructor() {
    private object Holder {
        val INSTANCE = SingletonWithLazyAndObject()
    }

    companion object {
        val instance: SingletonWithLazyAndObject by lazy { Holder.INSTANCE }
    }
}
```

3. Double-checked locking
```
abstract class UsersDatabase : RoomDatabase() {

    abstract fun userDao(): UserDao

    companion object {

        @Volatile private var INSTANCE: UsersDatabase? = null

        fun getInstance(context: Context): UsersDatabase =
                INSTANCE ?: synchronized(this) {
                    INSTANCE ?: buildDatabase(context).also { INSTANCE = it }
                }

        private fun buildDatabase(context: Context) =
                Room.databaseBuilder(context.applicationContext,
                        UsersDatabase::class.java, "Sample.db")
                        .build()
    }
}
```

4. Enum variation

[Links]
- https://github.com/android/architecture-components-samples/blob/master/BasicRxJavaSampleKotlin/app/src/main/java/com/example/android/observability/persistence/UsersDatabase.kt
- https://medium.com/swlh/singleton-design-pattern-with-kotlin-2e6c8d42fc11
- https://in-kotlin.com/design-patterns/singleton/
- https://stackoverflow.com/questions/6189099/lazy-loaded-singleton-double-checked-locking-vs-initialization-on-demand-holder
- https://stackoverflow.com/questions/35587652/kotlin-thread-safe-native-lazy-singleton-with-parameter
- https://bladecoder.medium.com/kotlin-singletons-with-argument-194ef06edd9e
- https://dongsik93.github.io/til/2022/08/01/til-kotlin-volatile/

2022-11-03 04:38 UTC, lyle0101 requested changes

2022-11-03 04:38 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        private val OK_INSTANCE by lazy { ApiResponse(null, null) }
여기서 by lazy 를 사용한 이유는 어떤걸까요?

2022-11-03 04:38 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        private val OK_INSTANCE by lazy { ApiResponse(null, null) }
이건 저도 더 고민해봐야 하기는 한데, OK_INSTANCE 라는 이름보다 더 나은 이름이 있으면 좋을 것 같습니다. 차라리 그냥 OK 라든지..?

2022-11-03 04:38 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        fun OK(): ApiResponse<*> {
이제서야 생각이 났는데 여기 메서드 이름들은 왜 전부 대문자로 되어 있는 건가요?

2022-11-03 09:41 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        fun OK(): ApiResponse<*> {
컨트롤러 메서드에서 return OK(...)로 ApiResponse static import해서 사용했을 때 가독성이 좋아서요. 아래 자바 코드 참고 부탁드려요.

```
return OK(
      new PostDto(
        postService.write(
          request.newPost(authentication.id, new Writer(authentication.email, authentication.name))
        )
      )
    );
```

2022-11-03 10:04 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        private val OK_INSTANCE by lazy { ApiResponse(null, null) }
by lazy를 사용한 이유는 효율적인 메모리 관리를 위해서입니다. Lazy initialization을 하면 ApiResponse가 생성될 때 OK_INSTANCE가 초기화되는 것이 아니라, OK_INSTANCE가 사용되는 상황에서 초기화가 이루어집니다. 

따라서, ApiResponse 인스턴스 생성 시 OK_INSTANCE 초기화 작업이 진행되지 않기 때문에 시간을 줄일 수 있습니다. 또한, by lazy 내부적으로 synchronized를 호출하기 때문에 thread-safe합니다. 

제 설명이 잘 이해되지 않는다면 아래 링크를 참고해주세요. 
- https://in-kotlin.com/design-patterns/interface-and-property-delegation/ (by lazy 키워드로 검색)
- https://stackoverflow.com/questions/36623177/property-initialization-using-by-lazy-vs-lateinit
- https://www.tutorialspoint.com/kotlin-property-initialization-using-by-lazy-vs-lateinit 
- https://dongsik93.github.io/til/2021/07/29/til-kotlin-lazy/ (lazy 동작 방식)

2022-11-03 10:08 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        private val OK_INSTANCE by lazy { ApiResponse(null, null) }
OK_INSTANCE 변수명에 대해 고민해봤는데, NO_DATA_OK나 OK_NO_DATA는 어떤가요?

2022-11-03 16:19 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        fun OK(): ApiResponse<*> {
- 메서드 이름 같은 경우는 [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case) 와 [네이버 핵데이 컨벤션](https://naver.github.io/hackday-conventions-java/#method-lower-camelcase) 등 여러 유명 컨벤션 가이드에서 lower camel case 로 작성하라고 되어 있기 때문에 나는 왠만하면 기존 컨벤션을 따르는게 좋다고 생각해!
- 메서드 이름을 lower camel case 로 한다면 너가 말한 것 처럼 static import 하면 눈에 잘 안보일 거라 자연스럽게 ApiResponse.ok 이런식으로 하게 될 것 같아!

2022-11-03 16:52 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        private val OK_INSTANCE by lazy { ApiResponse(null, null) }
OK_INSTANCE 변수명은 OK_NO_DATA 좋은 것 같아!

2022-11-04 02:30 UTC, lyle0101 commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        private val OK_INSTANCE by lazy { ApiResponse(null, null) }
처음에 by lazy 를 왜 사용했냐고 물어본건 ApiResponse 객체를 생성해서 할당하는 걸 굳이 by lazy 로 할 필요가 있는지 의문이 있어서 였어! 보통 by lazy 는 변수를 할당하는 로직이나 연산이 무거울 때 주로 사용하는 경우가 많으니까. 근데 너를 설득하려면 좀 더 확실한 근거가 있어야할 것 같다고 생각해서 아는 네카라쿠배 개발자 분께 by lazy 사용에 대해서 자세히 여쭤봤어! 그래서 결론적으로 아래 세 가지 이유 때문에 by lazy 를 사용하지 않고 그냥 `private val OK_NO_DATA = ApiResponse(null, null)` 이렇게 쓰는게 좋을 것 같아!

1. by lazy 를 쓰지 않아도 thread-safe 하다.
이거는 by lazy 를 쓰지 않고 일반 val 로 companion object 안에 선언한걸 java 로 디컴파일한 소스 코드야.
```
class Test1(
    private val name: String
)

class Test2 {
    companion object {
        private val test1 = Test1("test1")
    }
}
```
```
@Metadata(
   mv = {1, 6, 0},
   k = 1,
   d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u000e\n\u0002\b\u0002\u0018\u00002\u00020\u0001B\r\u0012\u0006\u0010\u0002\u001a\u00020\u0003¢\u0006\u0002\u0010\u0004R\u000e\u0010\u0002\u001a\u00020\u0003X\u0082\u0004¢\u0006\u0002\n\u0000¨\u0006\u0005"},
   d2 = {"LTest1;", "", "name", "", "(Ljava/lang/String;)V", "eylo-taxi-api.main"}
)
public final class Test1 {
   private final String name;

   public Test1(@NotNull String name) {
      Intrinsics.checkNotNullParameter(name, "name");
      super();
      this.name = name;
   }
}
// Test2.java
import kotlin.Metadata;
import kotlin.jvm.internal.DefaultConstructorMarker;
import org.jetbrains.annotations.NotNull;

@Metadata(
   mv = {1, 6, 0},
   k = 1,
   d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\u0018\u0000 \u00032\u00020\u0001:\u0001\u0003B\u0005¢\u0006\u0002\u0010\u0002¨\u0006\u0004"},
   d2 = {"LTest2;", "", "()V", "Companion", "eylo-taxi-api.main"}
)
public final class Test2 {
   private static final Test1 test1 = new Test1("test1");
   @NotNull
   public static final Companion Companion = new Companion((DefaultConstructorMarker)null);

   @Metadata(
      mv = {1, 6, 0},
      k = 1,
      d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0000\b\u0086\u0003\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002R\u000e\u0010\u0003\u001a\u00020\u0004X\u0082\u0004¢\u0006\u0002\n\u0000¨\u0006\u0005"},
      d2 = {"LTest2$Companion;", "", "()V", "test1", "LTest1;", "eylo-taxi-api.main"}
   )
   public static final class Companion {
      private Companion() {
      }

      // $FF: synthetic method
      public Companion(DefaultConstructorMarker $constructor_marker) {
         this();
      }
   }
}

```
보다시피 companion object 안의 private val 은 static final 로 처리된다는걸 알 수 있는데, static final 은 thread-safe 하기 때문에 thread-safety 때문에 by lazy 를 쓰지는 않아도 될 것 같다고 생각해.

참고 - https://stackoverflow.com/questions/25868200/is-a-public-static-final-int-thread-safe

2. 사용 시점에 초기화 하기 때문에 더 효율적 -> 그러나 값을 가져올 때마다 더 긴 로직을 거쳐야 해서 오히려 런타임에 호출 시간이 길어질 수 있음.
```
class Test1(
    private val name: String
)

class Test2 {
    companion object {
        private val test1 by lazy { Test1("test1") }
    }
}
```
```
@Metadata(
   mv = {1, 6, 0},
   k = 1,
   d1 = {"\u0000\u0012\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\n\u0002\u0010\u000e\n\u0002\b\u0002\u0018\u00002\u00020\u0001B\r\u0012\u0006\u0010\u0002\u001a\u00020\u0003¢\u0006\u0002\u0010\u0004R\u000e\u0010\u0002\u001a\u00020\u0003X\u0082\u0004¢\u0006\u0002\n\u0000¨\u0006\u0005"},
   d2 = {"LTest1;", "", "name", "", "(Ljava/lang/String;)V", "eylo-taxi-api.main"}
)
public final class Test1 {
   private final String name;

   public Test1(@NotNull String name) {
      Intrinsics.checkNotNullParameter(name, "name");
      super();
      this.name = name;
   }
}
// Test2.java
import kotlin.Lazy;
import kotlin.LazyKt;
import kotlin.Metadata;
import kotlin.jvm.functions.Function0;
import kotlin.jvm.internal.DefaultConstructorMarker;
import org.jetbrains.annotations.NotNull;

@Metadata(
   mv = {1, 6, 0},
   k = 1,
   d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0003\u0018\u0000 \u00032\u00020\u0001:\u0001\u0003B\u0005¢\u0006\u0002\u0010\u0002¨\u0006\u0004"},
   d2 = {"LTest2;", "", "()V", "Companion", "eylo-taxi-api.main"}
)
public final class Test2 {
   private static final Lazy test1$delegate;
   @NotNull
   public static final Companion Companion = new Companion((DefaultConstructorMarker)null);

   static {
      test1$delegate = LazyKt.lazy((Function0)null.INSTANCE);
   }

   @Metadata(
      mv = {1, 6, 0},
      k = 1,
      d1 = {"\u0000\u0014\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0005\b\u0086\u0003\u0018\u00002\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0002R\u001b\u0010\u0003\u001a\u00020\u00048BX\u0082\u0084\u0002¢\u0006\f\n\u0004\b\u0007\u0010\b\u001a\u0004\b\u0005\u0010\u0006¨\u0006\t"},
      d2 = {"LTest2$Companion;", "", "()V", "test1", "LTest1;", "getTest1", "()LTest1;", "test1$delegate", "Lkotlin/Lazy;", "eylo-taxi-api.main"}
   )
   public static final class Companion {
      private final Test1 getTest1() {
         Lazy var1 = Test2.test1$delegate;
         Companion var2 = Test2.Companion;
         Object var3 = null;
         return (Test1)var1.getValue();
      }

      private Companion() {
      }

      // $FF: synthetic method
      public Companion(DefaultConstructorMarker $constructor_marker) {
         this();
      }
   }
}
```
아까 단순히 private val 로 선언했을 때와 다르게 by lazy 로 선언하면 delegate 를 가져와서 getValue 하는 로직이 매번 들어가므로 오히려 런타임에서 호출 시간이 길어지게 돼. 결국은 클래스 초기화 시점에 static field 에 값을 초기화할 때 발생하는 지연 시간과 런타임 호출시에 발생하는 지연 시간의 차이인데 컴파일 시점에 초기화하는 시간이 훨씬 짧다고 생각해서 이번 경우에는 by lazy 가 더 효율적이지는 않다고 생각해!

3. 가독성, 코드 간결성 측면
조금 마이너한 부분이고 개발자마다 다를 수 있지만 일반적으로 by lazy 문법을 쓰는 것보다 private val 을 쓰는게 더 이해하기 쉽고 코드도 간결하다고 생각해! 그리고 다른 개발자 입장에서는 ApiResponse 클래스를 잘 모르는 상태에서 by lazy 를 본다면 ApiResponse 객체를 초기화하는게 무거운 작업이라고 생각할 수도 있을 것 같아!

2022-11-04 02:41 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        fun OK(): ApiResponse<*> {
- 프로젝트의 코드 컨벤션에 맞춰 작성하는 것이 좋으니 메서드명 lower case로 수정할게요~
- 전 static 메서드를 static import해서 사용하는 것을 선호하는데 어떻게 생각하시나요? 논의 후 규칙으로 정해야 할 것 같아요~ static import해서 사용하면 코드가 더 깔끔해진다는 장점이 있어 선호합니다.
- 해당 코드의 출처는 프로그래머스 백엔드 스터디 코드입니다~ 스터디 리더분들이 작성하신 코드에요. 또한, 아래 블로그에서도 대문자로 해당 메서드를 작성했습니다.
  https://zzang9ha.tistory.com/320

2022-11-04 02:42 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        private val OK_INSTANCE by lazy { ApiResponse(null, null) }
OK_NO_DATA 대신 EMPTY_OK는 어떤가요?

2022-11-04 03:00 UTC, kkangmj commented on src/main/kotlin/io/eylo/taxi/api/presentation/ApiResponse.kt
> +        private val OK_INSTANCE by lazy { ApiResponse(null, null) }
무거운 작업이라면 지연 초기화를 사용해 실행 시간과 메모리 효율을 개선할 수 있지만, ApiResponse의 경우에는 무거운 작업이라고 보기 어렵기 때문에 이 상황에서는 사용하지 않는 것이 좋다고 이해했습니다. 또한, 지연 초기화와 상관없이 자바로 디컴파일한 소스를 보니 Thread-safe하다는 점 이해했습니다.
따라서 지연 초기화는 사용하지 않도록 하겠습니다.

(이 이슈 덕분에 자바의 메모리 관리에 대해 다시 공부하게 되네요...)

2022-11-04 08:47 UTC, merged